vim.g.mapleader = "\\"
vim.g.maplocalleader = ","
vim.g.background = "light"
vim.opt.guifont = "Source Code Pro Light:h13"
vim.opt.conceallevel = 0
vim.opt.cursorline = true
vim.opt.number = true
vim.opt.relativenumber = true
vim.opt.mouse = "a"
vim.opt.clipboard = "unnamedplus"
vim.opt.undofile = true
vim.opt.undolevels = 10000
vim.opt.smartcase = true
vim.opt.updatetime = 250
vim.opt.timeoutlen = 700
vim.opt.completeopt = "menuone,noselect"
vim.opt.termguicolors = true
vim.opt.scrolloff = 20
vim.opt.splitbelow = true
vim.opt.splitright = true
vim.opt.breakindent = true
vim.opt.showmode = false
vim.opt.wrap = false
vim.opt.smoothscroll = true
vim.opt.spelllang = { "en" }
vim.opt.ignorecase = true
vim.opt.inccommand = "nosplit"
vim.opt.grepformat = "%f:%l:%c:%m"
vim.opt.grepprg = "rg --vimgrep"
vim.opt.wildmode = "longest:full,full"
