return {
  { "nvim-telescope/telescope.nvim", enabled = false },
  { "akinsho/bufferline.nvim", enabled = false },
  { "nvim-neo-tree/neo-tree.nvim", enabled = false },
  { "folke/noice.nvim", enabled = false },
  { "nvimdev/dashboard-nvim", enabled = false },
  { "echasnovski/mini.indentscope", enabled = false },
  { "folke/flash.nvim", enabled = false },
  { "RRethy/vim-illuminate", enabled = false },
  { "nvim-pack/nvim-spectre", enabled = false },
  { "stevearc/dressing.nvim", enabled = false },
  { "MunifTanjim/nui.nvim", enabled = false },
  { "folke/tokyonight.nvim", enabled = false },
  { "nvim-tresitter/nvim-treesitter-context", enabled = false },
  { "folke/persistence.nvim", enabled = false },
  { "echasnovski/mini.pairs", enabled = false },
  { "echasnovski/mini.ai", enabled = false },
  { "windwp/nvim-ts-autotag", enabled = false },
  { "garymjr/nvim-snippets", enabled = false },
  { "lukas-reineke/headlines.nvim", enabled = false },
  { "iamcco/markdown-preview.nvim", enabled = false },
}
